Dinampo branch
SeesonLau/Opticare pull request #28
Opened 2024-11-26 15:54 UTC by SirLKFD

Na add najud ang Clinic HomePage for an Eon🦖rawrrr

2024-11-26 16:07 UTC, SeesonLau requested changes
Do the following changes then request again.

2024-11-26 16:07 UTC, SeesonLau commented on public/global.css
> +}
add space

2024-11-26 16:07 UTC, SeesonLau commented on src/components/clinic/clinic-homepage.jsx
> +export default ClinicHomePage;
add space

2024-11-26 16:07 UTC, SeesonLau commented on src/components/clinic/clinic_styles/clinic-homepage-style.css
> +  }
add space

2024-11-26 16:07 UTC, SeesonLau commented on src/components/clinic/clinic_styles/profile-style.css
> +  }
add space

2024-11-26 16:07 UTC, SeesonLau commented on src/components/clinic/clinic_styles/calendar-style.css
i move ang .css to "styles" folder. adto pag create og folder for clinic

2024-11-26 16:07 UTC, SeesonLau commented on src/components/clinic/clinic_styles/clinic-homepage-style.css
i move ang .css to "styles" folder. adto pag create og folder for clinic

2024-11-26 16:07 UTC, SeesonLau commented on src/components/clinic/clinic_styles/patientlist-style.css
i move ang .css to "styles" folder. adto pag create og folder for clinic

2024-11-26 16:07 UTC, SeesonLau commented on src/components/clinic/clinic_styles/profile-style.css
i move ang .css to "styles" folder. adto pag create og folder for clinic

2024-11-26 16:07 UTC, SeesonLau commented on src/components/clinic/clinic_styles/visit-style.css
i move ang .css to "styles" folder. adto pag create og folder for clinic

2024-11-26 16:07 UTC, SeesonLau commented on src/components/clinic/clinic_styles/visit-style.css
> +  }
add space

2024-11-26 16:07 UTC, SeesonLau commented on src/image/default-photo.png
i recommend utilizing icons within "react" instead of uploading picture

2024-11-26 16:07 UTC, SeesonLau commented on src/page/users/clinic/ClinicHomePage.js
i believe wala natay page/users nga folder.
have this in .jsx

2024-11-26 16:07 UTC, SeesonLau commented on src/page/users/clinic/ClinicHomePage.module.css
move this to styles folder under clinic folder

2024-11-26 16:19 UTC, SirLKFD commented
Changes made

2024-11-26 17:02 UTC, SirLKFD commented
Used react icons for navbar and profile

2024-11-27 16:42 UTC, SeesonLau approved these changes

2024-11-27 16:42 UTC, merged